import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { ConvexHttpClient } from 'convex/browser';
import { api } from '../convex/_generated/api.js';
import { writeFileSync, mkdirSync } from 'node:fs';
process.loadEnvFile('.env.local');
const url = process.env.NEXT_PUBLIC_CONVEX_URL;
const site = process.env.NEXT_PUBLIC_CONVEX_SITE_URL;
if (!/^http:\/\/127\.0\.0\.1:\d+$/.test(url ?? '') || !/^http:\/\/127\.0\.0\.1:\d+$/.test(site ?? '')) throw new Error('This verification only creates synthetic accounts on a local deployment.');
const evidence = [];
const check = text => { evidence.push(text); console.log(`PASS ${text}`); };
async function account() {
  const client = new ConvexHttpClient(url);
  const result = await client.action(api.auth.signIn, { provider: 'password', params: { flow: 'signUp', email: `aura-test-${randomBytes(8).toString('hex')}@example.invalid`, password: randomBytes(24).toString('base64url') } });
  assert.ok(result.tokens?.token, 'Password signup must return a signed token');
  client.setAuth(result.tokens.token);
  assert.equal(await client.query(api.auth.isAuthenticated, {}), true);
  return client;
}
const alice = await account();
const bob = await account();
check('Two real password accounts authenticate with signed Convex tokens');
const data = { title: 'Synthetic AURA verification', transcript: 'Remember to check the chain fit.', summary: ['Check the chain fit.'], actions: ['Check the chain fit.'], tags: ['verification'], recordedAt: Date.now(), contextEnabled: false };
const id = await alice.mutation(api.notes.save, data);
assert.equal((await alice.query(api.notes.list, {})).length, 1);
assert.equal((await bob.query(api.notes.list, {})).length, 0);
await assert.rejects(() => bob.mutation(api.notes.archive, { id, archived: true }));
check('Real database persistence and account isolation');
await alice.mutation(api.profiles.save, { name: 'Test owner', about: 'Synthetic profile only.', goals: 'Evaluate a wearable.', preferences: 'Be concise.' });
const ingest = await alice.action(api.tokenActions.create, { name: 'Synthetic ingestion test', scope: 'ingest', autoContext: false });
const context = await alice.action(api.tokenActions.create, { name: 'Synthetic context test', scope: 'context', autoContext: false });
const auth = token => ({ Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' });
const body = JSON.stringify({ ...data, sourceId: 'synthetic-device-recording' });
const first = await fetch(`${site}/api/ingest`, { method: 'POST', headers: auth(ingest.secret), body });
assert.equal(first.status, 200);
const stored = await first.json();
const retry = await fetch(`${site}/api/ingest`, { method: 'POST', headers: auth(ingest.secret), body });
assert.equal((await retry.json()).id, stored.id);
assert.equal((await fetch(`${site}/api/context`, { headers: auth(ingest.secret) })).status, 401);
check('HTTP ingestion is idempotent and ingest credentials cannot read context');
const getContext = async () => (await fetch(`${site}/api/context`, { headers: auth(context.secret) })).json();
assert.equal((await getContext()).noteCount, 0);
await alice.mutation(api.notes.toggleContext, { id: stored.id, enabled: true });
const approved = await getContext();
assert.equal(approved.noteCount, 1);
assert.ok(approved.markdown.includes('Remember to check the chain fit.'));
check('Only explicitly approved notes enter the real HTTP Context Pack');
for (const method of ['initialize', 'tools/list', 'tools/call']) {
  const response = await fetch(`${site}/mcp`, { method: 'POST', headers: auth(context.secret), body: JSON.stringify({ jsonrpc: '2.0', id: method, method, params: method === 'tools/call' ? { name: 'get_aura_context', arguments: {} } : {} }) });
  assert.equal(response.status, 200);
  const reply = await response.json();
  assert.ok(reply.result);
  if (method === 'tools/call') assert.ok(reply.result.content[0].text.includes('Synthetic AURA verification'));
}
check('MCP initialize, tool discovery, and live context retrieval over HTTP');
const allTokens = await alice.query(api.tokens.list, {});
for (const token of allTokens) await alice.mutation(api.tokens.revoke, { id: token._id });
assert.equal((await fetch(`${site}/api/context`, { headers: auth(context.secret) })).status, 401);
for (const note of await alice.query(api.notes.list, {})) await alice.mutation(api.notes.archive, { id: note._id, archived: true });
await alice.action(api.auth.signOut, {});
await bob.action(api.auth.signOut, {});
check('Revoked connections immediately lose access; synthetic notes archived and sessions signed out');
mkdirSync('verification', { recursive: true });
writeFileSync('verification/local-integration.json', JSON.stringify({ testedAt: new Date().toISOString(), target: 'Real local Convex backend', checks: evidence, limitations: ['Synthetic data only', 'No physical BLE device', 'No cloud production deployment', 'No third-party AI chat OAuth connection'] }, null, 2));
