// Preserve the original nine-component move history and append C18 pin rotation.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const read=name=>fs.readFileSync(path.join(root,name));
const json=name=>JSON.parse(read(name));
const sha=data=>crypto.createHash('sha256').update(data).digest('hex');
const source=json('c18-source-sync.json');assert.equal(source.verified,true);
const proof=json('c18-symmetry-audit.json');assert.equal(proof.ok,true);
const manifest=json('../hardware/output/design-manifest.json');
assert.equal(sha(read('../hardware/output/design-manifest.json')),source.manifest_sha256);
assert.equal(sha(read('../hardware/src/placement-overrides.json')),source.source_after_sha256);
const before=json('pcb-placement-reference.json');
const after=Object.fromEntries(manifest.parts.map(part=>[part.ref,{x:part.x,y:part.y,r:part.r||0}]));
assert.equal(Object.keys(after).length,61);assert.deepEqual(after.C18,source.after);
assert.deepEqual({...after,C18:{...after.C18,r:before.C18.r}},before,'Unexpected mechanical reference change');
assert.ok([90,270].includes(before.C18.r));
const report=json('hardware-placement-sync.json');
const previousHash=report.followup_orientation_sync?.reference_before_sha256||sha(read('pcb-placement-reference.json'));
fs.writeFileSync(path.join(root,'pcb-placement-reference.json'),JSON.stringify(after,null,2)+'\n');
report.source_sha256=source.source_after_sha256;
report.after_sha256=sha(read('pcb-placement-reference.json'));
report.changes.C18.after=after.C18;
report.followup_orientation_sync={reference:'C18',reference_before_sha256:previousHash,source_before_rotation_degrees:90,source_after_rotation_degrees:270,canonical_visual_rotation_degrees:90,source_evidence:'c18-source-sync.json',symmetry_evidence:'c18-symmetry-audit.json',unchanged_xy:true,all_other_placements_unchanged:true,physical_body_unchanged:true,pcb_pin_rotation_exempted:false,original_native_freeze_evidence_is_historical:true};
fs.writeFileSync(path.join(root,'hardware-placement-sync.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({ok:true,components:61,source_c18:after.C18,reference_sha256:report.after_sha256}));
