import React from 'react';
import fs from 'node:fs';
import {Circuit} from '@tscircuit/core';
import {convertCircuitJsonToPcbSvg,convertCircuitJsonToSchematicSvg} from 'circuit-to-svg';
import AuraPendant from '../src/AuraPendant';
import {parts,boardSpec} from '../src/design';
const route=process.argv.includes('--route');
const circuit=new Circuit();
circuit.add(<AuraPendant route={route}/>);
console.log(`Rendering AURA with routing=${route}; ${parts.length} components.`);
const start=Date.now();
fs.writeFileSync('output/active-build.json',JSON.stringify({startedAt:new Date().toISOString(),route,router:'KRT WASM',pid:process.pid},null,2));
await circuit.renderUntilSettled();
const json=circuit.getCircuitJson();
const suffix=route?'routing-attempt':'placement';
fs.mkdirSync('output',{recursive:true});
fs.writeFileSync(`output/aura-${suffix}.circuit.json`,JSON.stringify(json,null,2));
fs.writeFileSync(`output/aura-${suffix}.pcb.svg`,convertCircuitJsonToPcbSvg(json,{width:1200,height:1600}));
fs.writeFileSync(`output/aura-${suffix}.schematic.svg`,convertCircuitJsonToSchematicSvg(json,{width:2400,height:1400}));
const errors=json.filter((e:any)=>e.type.includes('error'));
const counts=Object.fromEntries([...new Set(json.map((e:any)=>e.type))].map(t=>[t,json.filter((e:any)=>e.type===t).length]));
fs.writeFileSync(`output/${suffix}-validation.json`,JSON.stringify({createdAt:new Date().toISOString(),elapsedSeconds:(Date.now()-start)/1000,boardSpec,counts,errors},null,2));
fs.writeFileSync('output/design-manifest.json',JSON.stringify({boardSpec,parts},null,2));
const csv=(rows:any[][])=>rows.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n');
fs.writeFileSync('output/bom.csv',csv([['Reference','MPN','Description/value','Footprint','Qty','Review note'],...parts.map(p=>[p.ref,p.mpn,p.value,(p as any).fp,1,p.note||'Pin map crosscheck and sourcing review required'])]));
fs.writeFileSync('output/placement.csv',csv([['Reference','X_mm','Y_mm','Rotation_deg','Side'],...parts.map(p=>[p.ref,p.x,p.y,p.r||0,p.layer||'top'])]));
fs.writeFileSync('output/logical-netlist.json',JSON.stringify(Object.fromEntries([...new Set(parts.flatMap(p=>Object.values(p.pins)))].map(net=>[net,parts.flatMap(p=>Object.entries(p.pins).filter(([_,n])=>n===net).map(([pin])=>`${p.ref}.${pin}`))])),null,2));
console.log(JSON.stringify({suffix,elapsedSeconds:(Date.now()-start)/1000,counts,errors:errors.slice(0,8)},null,2));
