import fs from 'node:fs';
import assert from 'node:assert/strict';
const {parts}=JSON.parse(fs.readFileSync('output/design-manifest.json','utf8'));
const nets=JSON.parse(fs.readFileSync('output/logical-netlist.json','utf8'));
const byRef=Object.fromEntries(parts.map(p=>[p.ref,p]));
assert.equal(new Set(parts.map(p=>p.ref)).size,parts.length,'Unique reference designators');
for(const [net,pins]of Object.entries(nets))assert.ok(pins.length>=2,`Single-ended logical net ${net}`);
for(const p of parts)for(const n of p.nc||[])assert.ok(!p.pins[n],`NC pin wired: ${p.ref}.${n}`);
assert.equal(byRef.U1.pins[28],'V3');assert.equal(byRef.U1.pins[30],'V3');
assert.equal(byRef.SW1.pins[2],'MIC_VDD');assert.equal(byRef.SW1.pins[3],'GND');
assert.equal(byRef.U8.pins[8],'MIC_VDD');assert.equal(byRef.LED1.pins[2],'LED_RECORD_A');
assert.equal(byRef.R14.pins[1],'MIC_VDD');
assert.equal(byRef.MK1.pins[2],'GND');assert.equal(byRef.MK2.pins[2],'MIC_VDD');
assert.equal(byRef.U3.pins[6],'BAT_NTC');assert.ok(nets.BAT_NTC.includes('J2.3'));
assert.equal(byRef.R1.value,'4.02k');assert.equal(byRef.R2.value,'24k');
assert.equal(byRef.U4.pins[5],'V3');assert.equal(byRef.U7.pins[3],'RECORD_EN');
for(const ref of ['MK1','MK2'])assert.equal(byRef[ref].y-.77,8.5,'Acoustic hole aligns with case port');
const result={date:new Date().toISOString(),logicalChecks:'passed',components:parts.length,nets:Object.keys(nets).length,limitations:'This checks authored logical invariants only. It does not replace PCB connectivity, ERC, RF, battery or bench testing.'};
fs.writeFileSync('output/logical-checks.json',JSON.stringify(result,null,2));
console.log(result);
