import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { assemblyPose,partForName,travel } from './assembly-model.mjs';
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex').toUpperCase();
const html=fs.readFileSync('index.html','utf8');
const closing=html.match(/<p id="close-tagline"[^>]*>([\s\S]*?)<\/p>/)[1].replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
assert.equal(closing,'Capture the context of your life.');
const vtt=fs.readFileSync('captions.vtt','utf8');assert.ok(vtt.startsWith('WEBVTT'));
const cues=[...vtt.matchAll(/(\d{2}):(\d{2})\.(\d{3}) --> (\d{2}):(\d{2})\.(\d{3})/g)].map(c=>({start:Number(c[1])*60+Number(c[2])+Number(c[3])/1000,end:Number(c[4])*60+Number(c[5])+Number(c[6])/1000}));
assert.equal(cues.length,15);
cues.forEach((cue,i)=>{assert.ok(cue.end>cue.start);assert.ok(cue.end<=44);if(i)assert.ok(cue.start>=cues[i-1].end);});
assert.equal(cues.at(-1).end,44);
const prior=JSON.parse(fs.readFileSync('qa/assets-a03.json','utf8'));
const preserved=prior.assets.filter(a=>a.path.endsWith('.png'));
preserved.forEach(a=>assert.equal(hash(a.path),a.sha256));
const glb=fs.readFileSync('assets/aura-device.glb');
assert.equal(hash('assets/aura-device.glb'),hash('../../enclosure/aura-device.glb'));
const model=JSON.parse(glb.subarray(20,20+glb.readUInt32LE(12)).toString());
const grouped=Object.fromEntries(Object.keys(travel).map(part=>[part,model.nodes.filter(n=>partForName(n.name)===part).length]));
Object.values(grouped).forEach(n=>assert.ok(n>0));
assert.equal(assemblyPose(21.7).progress,0);assert.equal(assemblyPose(24.2).progress,1);assert.equal(assemblyPose(28.4).progress,0);
const seekTimes=[28.4,22.5,24.2,21.7,26.2,24.2];
const poses=seekTimes.map(time=>({time,...assemblyPose(time)}));
assert.deepEqual(poses[2],poses[5]);
const report={edition:'A03-context-assembly',primaryLine:closing,exactPrimaryLine:true,duration:44,captionsValid:true,cues:cues.length,lastCueEnd:cues.at(-1).end,preservedProductImagesVerified:preserved.length,glbMatchesSource:true,glbSha256:hash('assets/aura-device.glb'),groups:grouped,seekPoses:poses,cliVersion:'0.8.31'};
fs.writeFileSync('qa/context-validation.json',JSON.stringify(report,null,2)+'\n');
fs.writeFileSync('qa/captions-check.json',JSON.stringify({edition:report.edition,valid:true,cues:cues.length,lastCueEnd:44},null,2)+'\n');
const files=[...preserved.map(a=>a.path),'assets/aura-device.glb','assets/aura-score.wav','assets/studio-environment.bin','assets/studio-environment.json','assets/vendor/assembly.js'];
fs.writeFileSync('qa/assets-final.json',JSON.stringify({edition:report.edition,assets:files.map(path=>({path,bytes:fs.statSync(path).size,sha256:hash(path)}))},null,2)+'\n');
console.log(JSON.stringify(report,null,2));
